# Generated by Django 2.1.5 on 2019-01-17 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('hadm_id', models.IntegerField(primary_key=True, serialize=False)),
                ('intime', models.DateTimeField()),
                ('outtime', models.DateTimeField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='analytics.Admission')),
            ],
        ),
        migrations.CreateModel(
            name='BloodPressureStream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('bp_min', models.IntegerField()),
                ('bp_max', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Chartevent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField()),
                ('value', models.IntegerField()),
                ('datetime', models.DateTimeField()),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chartevents', to='analytics.Admission')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icd9_code', models.IntegerField()),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnoses', to='analytics.Admission')),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('drug', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.IntegerField(primary_key=True, serialize=False)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=20)),
                ('race', models.CharField(max_length=20)),
                ('postal_code', models.IntegerField()),
                ('occupation', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icd9_code', models.IntegerField()),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='analytics.Admission')),
            ],
        ),
        migrations.AddField(
            model_name='medication',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='analytics.Patient'),
        ),
        migrations.AddField(
            model_name='bloodpressurestream',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bpstreams', to='analytics.Patient'),
        ),
    ]
